apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracker-slack.fullname" . }}
  labels:
    {{- include "tracker-slack.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tracker-slack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tracker-slack.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpc.port }}
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /status
          #    port: metrics
          #readinessProbe:
          #  httpGet:
          #    path: /status
          #    port: metrics
          env:
            - name: TRACKER_SLACK_CHANNEL
              value: {{ .Values.env.tracker.slack | quote }}
            - name: TRACKER_HOST
              value: {{ .Values.env.tracker.host | quote }}
            - name: SLACK_VERIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "tracker-slack.fullname" . }}
                  key: SLACK_VERIFICATION_TOKEN
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "tracker-slack.fullname" . }}
                  key: SLACK_BOT_TOKEN
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "tracker-slack.fullname" . }}
                  key: SLACK_SIGNING_SECRET
          command:
            - /ko-app/tracker-slack
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
