{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracker-slack.fullname" . }}
  labels:
    {{- include "tracker-slack.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_VERIFICATION_TOKEN: {{  .Values.slack.verification_token | b64enc | quote }}
  SLACK_BOT_TOKEN: {{ .Values.slack.bot_token | b64enc | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.slack.signing_secret | b64enc | quote }}
{{- end }}
