apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: bananaops/tracker-slack
      ko: {}
deploy:
  helm:
    releases:
      - name: tracker-slack
        chartPath: helm/tracker-slack
        namespace: tracker
        createNamespace: true
        artifactOverrides:
          image: bananaops/tracker-slack
        imageStrategy:
          helm: {}
